from app.models import db, Comment


def seed_comments():
    comment1 = Comment(userId=8,mediaId=10,comment="Safest skatepark for kids of all ages, there's a dog park, batting cage, and a park around the corner about 1/2 mile. Grandson has been coming to skate here for years.")
    comment2 = Comment(userId=3,mediaId=36,comment="Great park but it is often closed. We are hear the day after thanksgiving. Kids are out of school and it is closed!! So everyone climbs the fence and skates. Either staff it or take the stupid fence down so the kids can use the tax payers resource")
    comment3 = Comment(userId=3,mediaId=30,comment="This is my favorite skate park I have ever been to. Not only does it have stuff for every level of skater, but there is a lot of space.")
    comment4 = Comment(userId=5,mediaId=48,comment="Only stopped by to watch the skaters for a while. It looks so surreal in real life! If you're lucky you'll see some really incredible stunts.")
    comment5 = Comment(userId=4,mediaId=9,comment="Sick little hidden gem in Eagle Rock. For all you dudes 30+, I suggest you show up at 7am on Saturday's and you'll have the bowl to yourselves")
    comment6 = Comment(userId=7,mediaId=43,comment="Nice clean park. Came for the wading pool, open on Wednesday's and fridays. It's perfect for small kids under 8 . Lifeguard on duty.")
    comment7 = Comment(userId=1,mediaId=49,comment="Parks aight, there's a sick bowl but the rest is meh. Some kook started yelling about helmets, the hallmark of bad parks. If you can drive to any other park, do it")
    comment8 = Comment(userId=1,mediaId=42,comment="Cute park! BBQ...grass... Play structure...basketball... Kiddie pool... Skateboard... Bathrooms... Parking is a pain because it's street parking... Ample shade....")
    comment9 = Comment(userId=10,mediaId=4,comment="This skatepark is good for kids and adults of all levels of skateboarding, scootering, and bmxing (if that's a word). I started here, rolling down the small banks and learning kick turns, now in just a month, I am catching air on a hip in the big bowl there.")
    comment10 = Comment(userId=10,mediaId=27,comment="Love this skatepark. Super laid back and cool people. Make sure you have helmet and pads with you!")
    comment11 = Comment(userId=7,mediaId=33,comment="Quick update! The park is still closed as of today!! Hopefully no one makes the same trip I did.")
    comment12 = Comment(userId=6,mediaId=12,comment="Free of Charge, Pet Friendly, Couple rails, one kinked, one flat. It's open early mornings, till very late, Pads and helmets aren't required, you sk8 at your own risk.")
    comment13 = Comment(userId=10,mediaId=34,comment="Beautiful park and great play areas for kids of all ages. Lots of shade! Only parallel parking on the streets. No parking lot.")
    comment14 = Comment(userId=7,mediaId=28,comment="I live up the street and i've known and passed by this skatepark for a long time and always found it to be kinda sketchy at first but once you start skating and get to know the skaters here, it's a very friendly and supportive community. yeah there are drug dealers, people who smoke/drink here, but everyone is very friendly towards other skaters. especially beginners")
    comment15 = Comment(userId=8,mediaId=48,comment="This a nice hidden park for the local community. I doubt many people drive through here. It is definitely well shaded with surrounding trees, equipped with updated playground, baseball field and a skate park. Really, Baseball field? Burbank domegraphics, I guess.")
    comment16 = Comment(userId=2,mediaId=45,comment="I used to go to this park and library back in jr high when I lived a block away. it wasn't that bad then, but now there are drug dealers, prostitutes, bums and cracked out people all over the place.")
    comment17 = Comment(userId=6,mediaId=19,comment="Great little park with fun lines and a killer pool-inspired bowl. Bring full pads or you can't skate -- elbows included.")
    comment18 = Comment(userId=6,mediaId=31,comment="Sick park for intermediate and advanced skaters. There are so many empty pools and ramps it's awesome!")
    comment19 = Comment(userId=10,mediaId=46,comment="anazing and fun with people who may teach you how to skate better and its all good vibes")
    comment20 = Comment(userId=5,mediaId=32,comment="Not even a skater guy but I thought this park was incredible. Reminded me of Tony hawk pro skater and the new Mid 90s movie. There was 100s of people watching the 10 or so skaters and everyone cheering them on to pull off tricks")
    comment21 = Comment(userId=10,mediaId=43,comment="This park is pretty awesome. It's definitely great for beginners, or those who are trying to get back into skateboarding or whatever riding. The locals are friendly. Just keep moving and be aware of others.")
    comment22 = Comment(userId=4,mediaId=29,comment="Really awesome skatepark, but they're supposed to open at 12... myself and several other cars were parked outside the gate & on the street until 12:30 before someone open we d the gate.")
    comment23 = Comment(userId=2,mediaId=39,comment="My grandson is a scooter and loved it. The other people we're very polite and well behaved. Surprisingly the skaters and scooter rider had respect for each other were considerate of each rider. I recommend this skate park...")
    comment24 = Comment(userId=1,mediaId=29,comment="Great for beginners to practice and learn, parking lot and plenty of parking on the street, and the environment is friendly with people of all ages and levels. In terms of safety, it's definitely one of the best spots")
    comment25 = Comment(userId=10,mediaId=43,comment="Really small park that is quiet and peaceful. Lots of people enjoying this area and so many cute equipment for kids to play on.")
    comment26 = Comment(userId=5,mediaId=3,comment="Awesome skatepark. Definitely worth seeing. Possibly worth skating on if you have better health insurance than I do. At my age I take that into consideration.")
    comment27 = Comment(userId=8,mediaId=26,comment="So I'm not a skater. So this review is purely on observation. Located in the same location as the Venice Boardwalk.")
    comment28 = Comment(userId=5,mediaId=11,comment="Pedlow is the best! The park has a little something for everyone to skate and have fun!! Get over here")
    comment29 = Comment(userId=3,mediaId=6,comment="Teeny tiny little concrete plaza with a not so bad 4'ish concrete mini ramp section, it was designed by someone with zero flow so you can not hit multiple sections unless you are a switch pro")
    comment30 = Comment(userId=2,mediaId=30,comment="I tried this park for the first time today. I haven't skated in like 6 years. This place doesn't make you feel intimidated. The people here are cool.")
    comment31 = Comment(userId=6,mediaId=43,comment="This park is nestled in a quiet neighborhood. There is a lot of greenery and is semi scenic. This is our favorite park in Glendale.")
    comment32 = Comment(userId=6,mediaId=35,comment="Our overall favorite skate park.")
    comment33 = Comment(userId=9,mediaId=9,comment="A great place to hangout and have the ability to relax. I would come with a friend to skateboard and there's no disappointment.")
    comment34 = Comment(userId=5,mediaId=4,comment="I love this park! I come here to walk and work. It's very well maintained and full of nice people. It has exercise equipment which is really cool and you see a lot of people using it. The playground is really cute and it has everything you want from a park.")
    comment35 = Comment(userId=8,mediaId=19,comment="I've been skating for over 10 years and the features in this park are great for all levels of skate, scooter and BMX. However, the City of Burbank has long ignored needs of the community and users of the park and turned the community and culture into a hostile environment, pitting members of the community against each other.")
    comment36 = Comment(userId=6,mediaId=30,comment="Good for young and old alike. Fun easy clover, A little bigger clover with a 1/4 capsule and a deep kidney. Sucks they charge you $15 to join but it's pretty fun and a geat taco place right across th street.")
    comment37 = Comment(userId=2,mediaId=26,comment="Pretty dope park, price isn't too bad and its not too crowded to you'll have time to get your runs in. Andre is cool, he always hooks people up and brings out free ice cream. These guys care about the sport and the scene and I highly recommend them.")
    comment38 = Comment(userId=2,mediaId=29,comment="My kids LOVE coming to scooter here. It's not too big so it's easy to keep your eyes on them. Most of the older kids are pretty friendly with the occasional bully here and there, usually younger boys. They offer snacks and drinks that my kids love to buy. Even hot dogs, corn dogs and cup of noodles just in case they are in need of food. I usually take my dog and walk her around while my kids play. Fun place for them to burn up that energy.")
    comment39 = Comment(userId=10,mediaId=26,comment="Seen alot of love seen alot creative skills and seen alot of brave peps. Boys to girls men to woman just doing there thing.")
    comment40 = Comment(userId=4,mediaId=23,comment="Awesome supervised skate park, I feel really comfortable being my kids to this park unlike other parks that are not supervised . Clean and fun. Just be aware of skate times,The hours are divided for skate , scooter, and Bmx. Highly recommend.")
    comment41 = Comment(userId=8,mediaId=1,comment="Had the most amazing Covid safe time at the skate park.. limited people, temp check and waiver signature..")
    comment42 = Comment(userId=1,mediaId=46,comment="So fun, great flow, lights until 9:30, free, pads optional, full pool, pretty much one of the most legit parks on the east side.")
    comment43 = Comment(userId=1,mediaId=36,comment="I quite like this park. Its nice, cozy, well taken care of. Has a skate park, outdoor gym, wading pool and lots of seating space. A little something for everyone. Its definitely improved since the renovation.")
    comment44 = Comment(userId=10,mediaId=35,comment="Too bad there are not too many skaters that live nearby. And I doubt too many parents would drop off their kids to skate in this park cuz its hella sketchy, even in the middle of the day.")
    comment45 = Comment(userId=2,mediaId=49,comment="Great place place to go with my kids. I have been going with them for over 5 years. Lots of place for skating, roller skating a and skate boarding. Unfortunately no basketball courts .")
    comment46 = Comment(userId=5,mediaId=42,comment="Beautiful park. Small but sweet. Very clean and they have several sports going on. The skate park is always full of kids and it's very safe. In a great neighborhood and plenty of parking. It's a sweet little secret in a sweet little neighborhood.")
    comment47 = Comment(userId=5,mediaId=13,comment="Bottom line is Venice has a better snake run, Santa Monica has better pools and bowls, and I've seen better street courses, but if you live in the valley, it's not bad. Bring water since it's always 110 degrees in the valley.")
    comment48 = Comment(userId=4,mediaId=14,comment="TLDR: Park is amazing, one of the staff members sucks.")
    comment49 = Comment(userId=8,mediaId=25,comment="Being an older skater I like a good mellow transition and even better flow of the park. Sadly this park had neither.")
    comment50 = Comment(userId=10,mediaId=49,comment="Really cool park kinda small though. Hot during the day too, really clean will be back definitely! Cool people")
    comment51 = Comment(userId=8,mediaId=11,comment="Absolutely amazing skatepark in the valley! Came here around 2006-ish for a summer skate camp and it was an awesome experience.")
    comment52 = Comment(userId=10,mediaId=47,comment="No scooters allowed. Their reasoning for this after reaching out is also very flawed. There is no reason why they should not allow them. Hopefully this changes in the future.")
    comment53 = Comment(userId=6,mediaId=17,comment="So much belly-aching over $3 charge in these reviews is petty. What's that, like the price of coke? You should definitely put this park in your circuit of great LA skate spots.")
    comment54 = Comment(userId=5,mediaId=5,comment="Nice park childhood memories. Nice place to relax and chill...")
    comment55 = Comment(userId=4,mediaId=47,comment="Great park! Safe for kids to skate! Beautiful small clean park with plenty of parking. Staff is always available to answer any questions and ensure the rules are followed for the skaters.")
    comment56 = Comment(userId=2,mediaId=13,comment="The Venice skate park is next to the beach in the heart of the Venice boardwalk. FYI if you want to skate here, you should know how to skate somewhat, the locals here don't like beginners killing the vibe of the skate park..")
    comment57 = Comment(userId=3,mediaId=50,comment="I have scouted a bunch of skate parks and this one had a very friendly crowd. Lots to do, its a cool course.")
    comment58 = Comment(userId=8,mediaId=21,comment="great skateboard park! great concrete work and design. especially love the kidney pool.")
    comment59 = Comment(userId=2,mediaId=37,comment="I love this park. Its newly built & only been open for not too long but it wasnt packed the day i went & i was there for about 4hrs or so.")
    comment60 = Comment(userId=8,mediaId=37,comment="Love the different obstacles and areas. Two decently sized bowls. No half pipe but you can turn a section with the spine into one. Wish there was more shade which is why this is only 4 stars.")
    comment61 = Comment(userId=8,mediaId=48,comment="Nice little free skate park with lots to do. Staff member is always on site to keep all the kids in check. Safe and fun!")
    comment62 = Comment(userId=8,mediaId=15,comment="Fun ledges and stairsets but there is one awkward kinked hubba that I can't skate other than that mad fun")
    comment63 = Comment(userId=4,mediaId=44,comment="Wow, wow and wow. This was an amazing little skating area with some skilled kids and adults rocking out on their skate boards.")
    comment64 = Comment(userId=3,mediaId=6,comment="This is a nice little park for your children. It's clean, the bathroom is clean and has the soft ground cover so if your kid falls it's not as damaging.")
    comment65 = Comment(userId=6,mediaId=15,comment="Come and skateboard or see some amazing skateboarders. A fun experience.")
    comment66 = Comment(userId=7,mediaId=39,comment="It has a lot of open flat lay out area to skate around if you aren't about the bowl/pool life, but still want to catch some little hills. It's a cool spot to practice on some tricks and skills.")
    comment67 = Comment(userId=5,mediaId=28,comment="Definitely a park that every skater needs to visit at least once.")
    comment68 = Comment(userId=3,mediaId=50,comment="We had so much fun here. I like that they enforce everyone to wear pads and helmets. Keep the community safe. I'd wish they opened on weekdays during the day. But I guess weekends they have longer hours.")
    comment69 = Comment(userId=6,mediaId=35,comment="Great for street skaters, especially experienced street skaters. Not a lot of transition if that's your thing. Covid-19 hours are 12-5 pm, meaning you can't even go enjoy the park when it's empty and social distancing is possible.")
    comment70 = Comment(userId=1,mediaId=21,comment="Very cool skatepark but they should clean before they open also they should make it bigger with smaller ramps for the kids and more ledges.One thing I hate tho is that their is always drunk older people that shouldn't be in the restroom.")
    comment71 = Comment(userId=8,mediaId=1,comment="Close to Florence station. Good size ball and rest park for watching amateur ball park games during the week. Semi decently maintained.")
    comment72 = Comment(userId=3,mediaId=17,comment="This is the best skate park in the valley. I've learn a lot of new tricks on this park.")
    comment73 = Comment(userId=3,mediaId=2,comment="very cool skate park and especially the staff shout out to my bro rob for giving me some staples to fix my pants cuz i had a rip please check out this skatepark you have a fun time and the people are pretty chill at this park")
    comment74 = Comment(userId=7,mediaId=17,comment="Good shade, friendly staff. Great for younger skaters but I see a lot of veterans here too. At $3 the price is right.")
    comment75 = Comment(userId=2,mediaId=24,comment="They make you pay to skate and grown men must wear elbow and knee pads. Seriously? Good luck")
    comment76 = Comment(userId=9,mediaId=31,comment="Nice spot to skate. Could use more vertical . Was grateful for the shade trees on a hot day. Very affordable fruit and snacks were available from nearby vendors")
    comment77 = Comment(userId=2,mediaId=22,comment="This is by far the worse skatepark ever. They have scheduled times. Like wth is that? You gotta wear full pads and pay? This place is full of spoiled little kids that just want to go down ramps. This is a prime example of what the world is coming to. You can't even go to skatepark and skate. If I could rate this place any lower, I would.")
    comment78 = Comment(userId=5,mediaId=34,comment="itz great it needs more scooters there i was like the only one")
    comment79 = Comment(userId=2,mediaId=20,comment="If you're looking for a true Venice Beach experience, make sure to stop by the skate park and watch how the crowds gather around the amazing skaters.")
    comment80 = Comment(userId=1,mediaId=16,comment="Kids smoking . My son's skate tool was stolen from his own hands from another skater.")

    db.session.add(comment1)
    db.session.add(comment2)
    db.session.add(comment3)
    db.session.add(comment4)
    db.session.add(comment5)
    db.session.add(comment6)
    db.session.add(comment7)
    db.session.add(comment8)
    db.session.add(comment9)
    db.session.add(comment10)
    db.session.add(comment11)
    db.session.add(comment12)
    db.session.add(comment13)
    db.session.add(comment14)
    db.session.add(comment15)
    db.session.add(comment16)
    db.session.add(comment17)
    db.session.add(comment18)
    db.session.add(comment19)
    db.session.add(comment20)
    db.session.add(comment21)
    db.session.add(comment22)
    db.session.add(comment23)
    db.session.add(comment24)
    db.session.add(comment25)
    db.session.add(comment26)
    db.session.add(comment27)
    db.session.add(comment28)
    db.session.add(comment29)
    db.session.add(comment30)
    db.session.add(comment31)
    db.session.add(comment32)
    db.session.add(comment33)
    db.session.add(comment34)
    db.session.add(comment35)
    db.session.add(comment36)
    db.session.add(comment37)
    db.session.add(comment38)
    db.session.add(comment39)
    db.session.add(comment40)
    db.session.add(comment41)
    db.session.add(comment42)
    db.session.add(comment43)
    db.session.add(comment44)
    db.session.add(comment45)
    db.session.add(comment46)
    db.session.add(comment47)
    db.session.add(comment48)
    db.session.add(comment49)
    db.session.add(comment50)
    db.session.add(comment51)
    db.session.add(comment52)
    db.session.add(comment53)
    db.session.add(comment54)
    db.session.add(comment55)
    db.session.add(comment56)
    db.session.add(comment57)
    db.session.add(comment58)
    db.session.add(comment59)
    db.session.add(comment60)
    db.session.add(comment61)
    db.session.add(comment62)
    db.session.add(comment63)
    db.session.add(comment64)
    db.session.add(comment65)
    db.session.add(comment66)
    db.session.add(comment67)
    db.session.add(comment68)
    db.session.add(comment69)
    db.session.add(comment70)
    db.session.add(comment71)
    db.session.add(comment72)
    db.session.add(comment73)
    db.session.add(comment74)
    db.session.add(comment75)
    db.session.add(comment76)
    db.session.add(comment77)
    db.session.add(comment78)
    db.session.add(comment79)
    db.session.add(comment80)
    db.session.commit()

def undo_comments():
    db.session.execute('TRUNCATE comments RESTART IDENTITY CASCADE;')
    db.session.commit()
