"""deleted followers table

Revision ID: a8975fe90871
Revises: 0b34bd03b9d5
Create Date: 2021-08-16 12:47:03.599867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8975fe90871'
down_revision = '0b34bd03b9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followerId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followerId'], ['users.id'], name='followers_followerId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='followers_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='followers_pkey')
    )
    op.drop_table('follows')
    # ### end Alembic commands ###
